### ISSUE TITLE
Still don’t work 

### ISSUE THREAD

**Issue by j7evn** [Gamzakov/SberbankBypass12#2]
Heya. Still got issues with sberbank app. 
Latest version of sber
Ios 12.4 u0 3.7.0 b3
![7C929926-904F-42E9-B4C5-AF11364746BC](https://user-images.githubusercontent.com/31626094/71432226-b7c3dc00-26f9-11ea-93f6-3e54eae15590.png)

**Comment by alekseezy** [comment]
Привет, переустанавливал сбер?
Твик обновлен до 0.0-3-2? Choicy, TweakRestrictor отключены для сбера? Можно попробовать Liberty + SberbankBypass некоторым помогало
25 дек. 2019 г., 07:34 +0300, j7evn <notifications@github.com>, писал:

**Comment by j7evn** [comment]
> Привет, переустанавливал сбер? Твик обновлен до 0.0-3-2? Choicy, TweakRestrictor отключены для сбера? Можно попробовать Liberty + SberbankBypass некоторым помогало 25 дек. 2019 г., 07:34 +0300, j7evn <notifications@github.com>, писал:
> […](#)

Да, пробовал переустановку. Твиков что ты написал не имею. 
Есть UnSub там отключил всё. Версия  твоего твика последняя... такое ощущение, что в системе у меня что то поломалось
Тк проблема началась вроде с u0 3.5 если память не изменяет. Но если раньше нельзя было вообще отправлять
То сейчас пишет мол только по шаблонам

**Comment by j7evn** [comment]
Да, переустанавливал. 
Твик последней версии из реджейл. 
Твиков что ты написал нет
Есть UnSub но там все отключено...

**Comment by j7evn** [comment]
И что за Liberty+ ?

**Comment by alekseezy** [comment]
Вот такую связку поставить активировать в Liberty для сбера переустановить сбер удалить watch можно так попробовать
25 дек. 2019 г., 20:22 +0300, j7evn <notifications@github.com>, писал:

**Comment by j7evn** [comment]
> Вот такую связку поставить активировать в Liberty для сбера переустановить сбер удалить watch можно так попробовать 25 дек. 2019 г., 20:22 +0300, j7evn <notifications@github.com>, писал:
> […](#)

Зарабоооооотала!!
Я уже перестал надеяться, спасибо добрый человек. Куда на пиво кидать?

**Comment by alekseezy** [comment]
Да не за что :)

Кнопка доната есть в настройках твика, а так вот ссылка: https://www.paypal.me/GamzakovDev
25 дек. 2019 г., 21:49 +0300, j7evn <notifications@github.com>, писал:
